### ISSUE TITLE
原代码缺失严重，无法运行。已经在本地重构，可以运行，有需要可以联系。

### ISSUE THREAD

**Issue by riskycheng** [RuiZeWu/Android-OpenPose#6]
原代码缺失严重，无法运行。已经在本地重构，可以运行，有需要可以联系。
在SNPE 1.25 GPU runtime上， 845 平台 400ms/frame.

**Comment by yinguoxiangyi** [comment]
老铁，留个邮箱呗，非常感谢

**Comment by jianwenzhou** [comment]
老铁，非常感谢，409820759@qq.com

**Comment by yinguoxiangyi** [comment]
> 老铁，非常感谢，[409820759@qq.com](mailto:409820759@qq.com)

你收到项目文件了吗？

**Comment by doinsane** [comment]
Hi @yinguoxiangyi    方便重發嗎 我也想測試  iamyuan@gmail.com 感謝

**Comment by fensite** [comment]
857458455@qq.com    @riskycheng @jianwenzhou 方便发一下吗？多谢老铁

**Comment by yinguoxiangyi** [comment]
1522346936@qq.com @riskycheng @jianwenzhou 楼主咋不回呀

**Comment by cheng3311** [comment]
2992122755@qq.com  @riskycheng @yinguoxiangyi @yuanwang1980 方便给我一份么？十分感谢

**Comment by nwpu2017300135** [comment]
838966118@qq.com 老哥有空发一份呗

**Comment by iReuters** [comment]
982457331@qq.com  @riskycheng @yinguoxiangyi @jianwenzhou @yuanwang1980 有人收到了吗，能不能给我一份

**Comment by I-am-Lucas-Law-Sau-Ho** [comment]
我也可以拿一份吗？ lucaslawsauho@gmail.com

**Comment by I-am-Lucas-Law-Sau-Ho** [comment]
我也可以拿一份吗？ @riskycheng @MorningMyFriend  lucaslawsauho@gmail.com

**Comment by ling7314** [comment]
rafehwang@gmail.com   我也想要一份，可以吗？谢谢您

**Comment by ling7314** [comment]
> 原代码缺失严重，无法运行。已经在本地重构，可以运行，有需要可以联系。 在SNPE 1.25 GPU runtime上， 845 平台 400ms/frame.
作者你好，我急需这份代码作为参考，请您有时间回复给我一份，谢谢您
